apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: game-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 192.168.101.2:5000/gateway:v1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080  # HTTP 端口
          name: http
        - containerPort: 8081  # WebSocket 端口
          name: websocket
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_NAME
          value: "gateway-service"
        - name: HTTP_PORT
          value: "8080"
        - name: WEBSOCKET_PORT
          value: "8081"
        - name: CONFIG_LOCATION
          value: "nacos"
        - name: REGISTRY_TYPE
          value: "nacos"
        - name: NACOS_SERVER
          value: "nacos.game-server.svc.cluster.local"
        - name: "NACOS_PORT"
          value: "8848"
        - name: NACOS_NAMESPACE
          value: "dcb54ac9-b24b-4851-95a1-06f18f6a9b57"
        - name: NACOS_GROUP
          value: "DEFAULT_GROUP"
        - name: NACOS_TIMEOUT
          value: "5000"
        - name: NACOS_USERNAME
          value: ""
        - name: NACOS_PASSWORD
          value: ""
        - name: APP_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
