apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: game-server
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'redis-cluster'
        static_configs:
          - targets: ['redis-cluster-monitor.game-server.svc.cluster.local:9121']
        metrics_path: /metrics
