apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nacos-cluster.fullname" . }}-cluster-conf
  namespace: {{ .Values.namespace }}
data:
  cluster.conf: |
    {{- range $i, $e := until (int .Values.replicaCount) }}
    {{ include "nacos-cluster.fullname" $ }}-{{ $i }}.{{ $.Values.service.headless.name }}.{{ $.Values.namespace }}.svc.cluster.local:8848
    {{- end }}