apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headless.name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ include "nacos-cluster.name" . }}
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.client.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "nacos-cluster.name" . }}
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
  type: {{ .Values.service.client.type }}