// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: internal/pb/game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	mi := &file_internal_pb_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_game_proto_rawDescGZIP(), []int{0}
}

func (x *JoinGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_internal_pb_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_game_proto_rawDescGZIP(), []int{1}
}

func (x *JoinGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LeaveGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGameRequest) Reset() {
	*x = LeaveGameRequest{}
	mi := &file_internal_pb_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGameRequest) ProtoMessage() {}

func (x *LeaveGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGameRequest.ProtoReflect.Descriptor instead.
func (*LeaveGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_game_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LeaveGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type LeaveGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGameResponse) Reset() {
	*x = LeaveGameResponse{}
	mi := &file_internal_pb_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGameResponse) ProtoMessage() {}

func (x *LeaveGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGameResponse.ProtoReflect.Descriptor instead.
func (*LeaveGameResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_game_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateRequest) Reset() {
	*x = GameStateRequest{}
	mi := &file_internal_pb_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateRequest) ProtoMessage() {}

func (x *GameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateRequest.ProtoReflect.Descriptor instead.
func (*GameStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameStateRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Players       []string               `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateResponse) Reset() {
	*x = GameStateResponse{}
	mi := &file_internal_pb_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateResponse) ProtoMessage() {}

func (x *GameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateResponse.ProtoReflect.Descriptor instead.
func (*GameStateResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GameStateResponse) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActionRequest) Reset() {
	*x = PlayerActionRequest{}
	mi := &file_internal_pb_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionRequest) ProtoMessage() {}

func (x *PlayerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionRequest.ProtoReflect.Descriptor instead.
func (*PlayerActionRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerActionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerActionRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlayerActionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PlayerActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActionResponse) Reset() {
	*x = PlayerActionResponse{}
	mi := &file_internal_pb_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionResponse) ProtoMessage() {}

func (x *PlayerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionResponse.ProtoReflect.Descriptor instead.
func (*PlayerActionResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_game_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayerActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_pb_game_proto protoreflect.FileDescriptor

const file_internal_pb_game_proto_rawDesc = "" +
	"\n" +
	"\x16internal/pb/game.proto\x12\x04game\"G\n" +
	"\x0fJoinGameRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"F\n" +
	"\x10JoinGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x10LeaveGameRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\"-\n" +
	"\x11LeaveGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x10GameStateRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"C\n" +
	"\x11GameStateResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\aplayers\x18\x02 \x03(\tR\aplayers\"}\n" +
	"\x13PlayerActionRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"J\n" +
	"\x14PlayerActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8e\x02\n" +
	"\vGameService\x129\n" +
	"\bJoinGame\x12\x15.game.JoinGameRequest\x1a\x16.game.JoinGameResponse\x12<\n" +
	"\tLeaveGame\x12\x16.game.LeaveGameRequest\x1a\x17.game.LeaveGameResponse\x12?\n" +
	"\fGetGameState\x12\x16.game.GameStateRequest\x1a\x17.game.GameStateResponse\x12E\n" +
	"\fPlayerAction\x12\x19.game.PlayerActionRequest\x1a\x1a.game.PlayerActionResponseB\rZ\vinternal/pbb\x06proto3"

var (
	file_internal_pb_game_proto_rawDescOnce sync.Once
	file_internal_pb_game_proto_rawDescData []byte
)

func file_internal_pb_game_proto_rawDescGZIP() []byte {
	file_internal_pb_game_proto_rawDescOnce.Do(func() {
		file_internal_pb_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_game_proto_rawDesc), len(file_internal_pb_game_proto_rawDesc)))
	})
	return file_internal_pb_game_proto_rawDescData
}

var file_internal_pb_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_pb_game_proto_goTypes = []any{
	(*JoinGameRequest)(nil),      // 0: game.JoinGameRequest
	(*JoinGameResponse)(nil),     // 1: game.JoinGameResponse
	(*LeaveGameRequest)(nil),     // 2: game.LeaveGameRequest
	(*LeaveGameResponse)(nil),    // 3: game.LeaveGameResponse
	(*GameStateRequest)(nil),     // 4: game.GameStateRequest
	(*GameStateResponse)(nil),    // 5: game.GameStateResponse
	(*PlayerActionRequest)(nil),  // 6: game.PlayerActionRequest
	(*PlayerActionResponse)(nil), // 7: game.PlayerActionResponse
}
var file_internal_pb_game_proto_depIdxs = []int32{
	0, // 0: game.GameService.JoinGame:input_type -> game.JoinGameRequest
	2, // 1: game.GameService.LeaveGame:input_type -> game.LeaveGameRequest
	4, // 2: game.GameService.GetGameState:input_type -> game.GameStateRequest
	6, // 3: game.GameService.PlayerAction:input_type -> game.PlayerActionRequest
	1, // 4: game.GameService.JoinGame:output_type -> game.JoinGameResponse
	3, // 5: game.GameService.LeaveGame:output_type -> game.LeaveGameResponse
	5, // 6: game.GameService.GetGameState:output_type -> game.GameStateResponse
	7, // 7: game.GameService.PlayerAction:output_type -> game.PlayerActionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_game_proto_init() }
func file_internal_pb_game_proto_init() {
	if File_internal_pb_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_game_proto_rawDesc), len(file_internal_pb_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_game_proto_goTypes,
		DependencyIndexes: file_internal_pb_game_proto_depIdxs,
		MessageInfos:      file_internal_pb_game_proto_msgTypes,
	}.Build()
	File_internal_pb_game_proto = out.File
	file_internal_pb_game_proto_goTypes = nil
	file_internal_pb_game_proto_depIdxs = nil
}
