// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: internal/pb/leaderboard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaderboard   string                 `protobuf:"bytes,1,opt,name=leaderboard,proto3" json:"leaderboard,omitempty"` // 排行榜类型
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportScoreRequest) Reset() {
	*x = ReportScoreRequest{}
	mi := &file_internal_pb_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportScoreRequest) ProtoMessage() {}

func (x *ReportScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportScoreRequest.ProtoReflect.Descriptor instead.
func (*ReportScoreRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *ReportScoreRequest) GetLeaderboard() string {
	if x != nil {
		return x.Leaderboard
	}
	return ""
}

func (x *ReportScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReportScoreRequest) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ReportScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportScoreResponse) Reset() {
	*x = ReportScoreResponse{}
	mi := &file_internal_pb_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportScoreResponse) ProtoMessage() {}

func (x *ReportScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportScoreResponse.ProtoReflect.Descriptor instead.
func (*ReportScoreResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *ReportScoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaderboard   string                 `protobuf:"bytes,1,opt,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_internal_pb_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeaderboardRequest) GetLeaderboard() string {
	if x != nil {
		return x.Leaderboard
	}
	return ""
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_internal_pb_leaderboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_leaderboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_leaderboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_internal_pb_leaderboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_leaderboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_internal_pb_leaderboard_proto_rawDescGZIP(), []int{4}
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GetRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaderboard   string                 `protobuf:"bytes,1,opt,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankRequest) Reset() {
	*x = GetRankRequest{}
	mi := &file_internal_pb_leaderboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankRequest) ProtoMessage() {}

func (x *GetRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_leaderboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankRequest.ProtoReflect.Descriptor instead.
func (*GetRankRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_leaderboard_proto_rawDescGZIP(), []int{5}
}

func (x *GetRankRequest) GetLeaderboard() string {
	if x != nil {
		return x.Leaderboard
	}
	return ""
}

func (x *GetRankRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankResponse) Reset() {
	*x = GetRankResponse{}
	mi := &file_internal_pb_leaderboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankResponse) ProtoMessage() {}

func (x *GetRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_leaderboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankResponse.ProtoReflect.Descriptor instead.
func (*GetRankResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_leaderboard_proto_rawDescGZIP(), []int{6}
}

func (x *GetRankResponse) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GetRankResponse) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_internal_pb_leaderboard_proto protoreflect.FileDescriptor

const file_internal_pb_leaderboard_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/pb/leaderboard.proto\x12\vleaderboard\"e\n" +
	"\x12ReportScoreRequest\x12 \n" +
	"\vleaderboard\x18\x01 \x01(\tR\vleaderboard\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\"I\n" +
	"\x13ReportScoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x15GetLeaderboardRequest\x12 \n" +
	"\vleaderboard\x18\x01 \x01(\tR\vleaderboard\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"Q\n" +
	"\x16GetLeaderboardResponse\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.leaderboard.LeaderboardEntryR\aentries\"U\n" +
	"\x10LeaderboardEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\"K\n" +
	"\x0eGetRankRequest\x12 \n" +
	"\vleaderboard\x18\x01 \x01(\tR\vleaderboard\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\";\n" +
	"\x0fGetRankResponse\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score2\x87\x02\n" +
	"\x12LeaderboardService\x12P\n" +
	"\vReportScore\x12\x1f.leaderboard.ReportScoreRequest\x1a .leaderboard.ReportScoreResponse\x12Y\n" +
	"\x0eGetLeaderboard\x12\".leaderboard.GetLeaderboardRequest\x1a#.leaderboard.GetLeaderboardResponse\x12D\n" +
	"\aGetRank\x12\x1b.leaderboard.GetRankRequest\x1a\x1c.leaderboard.GetRankResponseB\rZ\vinternal/pbb\x06proto3"

var (
	file_internal_pb_leaderboard_proto_rawDescOnce sync.Once
	file_internal_pb_leaderboard_proto_rawDescData []byte
)

func file_internal_pb_leaderboard_proto_rawDescGZIP() []byte {
	file_internal_pb_leaderboard_proto_rawDescOnce.Do(func() {
		file_internal_pb_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_leaderboard_proto_rawDesc), len(file_internal_pb_leaderboard_proto_rawDesc)))
	})
	return file_internal_pb_leaderboard_proto_rawDescData
}

var file_internal_pb_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_pb_leaderboard_proto_goTypes = []any{
	(*ReportScoreRequest)(nil),     // 0: leaderboard.ReportScoreRequest
	(*ReportScoreResponse)(nil),    // 1: leaderboard.ReportScoreResponse
	(*GetLeaderboardRequest)(nil),  // 2: leaderboard.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil), // 3: leaderboard.GetLeaderboardResponse
	(*LeaderboardEntry)(nil),       // 4: leaderboard.LeaderboardEntry
	(*GetRankRequest)(nil),         // 5: leaderboard.GetRankRequest
	(*GetRankResponse)(nil),        // 6: leaderboard.GetRankResponse
}
var file_internal_pb_leaderboard_proto_depIdxs = []int32{
	4, // 0: leaderboard.GetLeaderboardResponse.entries:type_name -> leaderboard.LeaderboardEntry
	0, // 1: leaderboard.LeaderboardService.ReportScore:input_type -> leaderboard.ReportScoreRequest
	2, // 2: leaderboard.LeaderboardService.GetLeaderboard:input_type -> leaderboard.GetLeaderboardRequest
	5, // 3: leaderboard.LeaderboardService.GetRank:input_type -> leaderboard.GetRankRequest
	1, // 4: leaderboard.LeaderboardService.ReportScore:output_type -> leaderboard.ReportScoreResponse
	3, // 5: leaderboard.LeaderboardService.GetLeaderboard:output_type -> leaderboard.GetLeaderboardResponse
	6, // 6: leaderboard.LeaderboardService.GetRank:output_type -> leaderboard.GetRankResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pb_leaderboard_proto_init() }
func file_internal_pb_leaderboard_proto_init() {
	if File_internal_pb_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_leaderboard_proto_rawDesc), len(file_internal_pb_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_leaderboard_proto_goTypes,
		DependencyIndexes: file_internal_pb_leaderboard_proto_depIdxs,
		MessageInfos:      file_internal_pb_leaderboard_proto_msgTypes,
	}.Build()
	File_internal_pb_leaderboard_proto = out.File
	file_internal_pb_leaderboard_proto_goTypes = nil
	file_internal_pb_leaderboard_proto_depIdxs = nil
}
