// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: internal/pb/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`             // 物品实例ID
	TemplateId    int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // 物品模板ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                // 物品名称
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`                             // 数量
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`                               // 物品类型
	SubType       int32                  `protobuf:"varint,6,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`          // 物品子类型
	Color         int32                  `protobuf:"varint,7,opt,name=color,proto3" json:"color,omitempty"`                             // 物品品质
	Stack         int32                  `protobuf:"varint,8,opt,name=stack,proto3" json:"stack,omitempty"`                             // 堆叠上限
	Equipped      bool                   `protobuf:"varint,9,opt,name=equipped,proto3" json:"equipped,omitempty"`                       // 是否已装备
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_internal_pb_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{4}
}

func (x *Item) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Item) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Item) GetSubType() int32 {
	if x != nil {
		return x.SubType
	}
	return 0
}

func (x *Item) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *Item) GetStack() int32 {
	if x != nil {
		return x.Stack
	}
	return 0
}

func (x *Item) GetEquipped() bool {
	if x != nil {
		return x.Equipped
	}
	return false
}

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_internal_pb_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{5}
}

func (x *Inventory) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Inventory) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetInventoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetInventoryResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TplId         int64                  `protobuf:"varint,2,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{8}
}

func (x *AddItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddItemRequest) GetTplId() int64 {
	if x != nil {
		return x.TplId
	}
	return 0
}

func (x *AddItemRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{9}
}

func (x *AddItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveItemRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *RemoveItemRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemResponse) Reset() {
	*x = RemoveItemResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemResponse) ProtoMessage() {}

func (x *RemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UseItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemRequest) Reset() {
	*x = UseItemRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemRequest) ProtoMessage() {}

func (x *UseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemRequest.ProtoReflect.Descriptor instead.
func (*UseItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{12}
}

func (x *UseItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UseItemRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UseItemRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UseItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemResponse) Reset() {
	*x = UseItemResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemResponse) ProtoMessage() {}

func (x *UseItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemResponse.ProtoReflect.Descriptor instead.
func (*UseItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{13}
}

func (x *UseItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 装备信息
type Equipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 装备实例ID
	TemplateId    int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // 装备模板ID
	Slot          int32                  `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`                               // 装备槽位
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                // 装备名称
	Properties    string                 `protobuf:"bytes,5,opt,name=properties,proto3" json:"properties,omitempty"`                    // JSON格式的装备属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Equipment) Reset() {
	*x = Equipment{}
	mi := &file_internal_pb_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Equipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equipment) ProtoMessage() {}

func (x *Equipment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equipment.ProtoReflect.Descriptor instead.
func (*Equipment) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{14}
}

func (x *Equipment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Equipment) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *Equipment) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Equipment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Equipment) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

// 获取装备请求
type GetEquipmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquipmentsRequest) Reset() {
	*x = GetEquipmentsRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquipmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipmentsRequest) ProtoMessage() {}

func (x *GetEquipmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipmentsRequest.ProtoReflect.Descriptor instead.
func (*GetEquipmentsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetEquipmentsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取装备响应
type GetEquipmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Equipments    []*Equipment           `protobuf:"bytes,1,rep,name=equipments,proto3" json:"equipments,omitempty"` // 装备列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquipmentsResponse) Reset() {
	*x = GetEquipmentsResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquipmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipmentsResponse) ProtoMessage() {}

func (x *GetEquipmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipmentsResponse.ProtoReflect.Descriptor instead.
func (*GetEquipmentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetEquipmentsResponse) GetEquipments() []*Equipment {
	if x != nil {
		return x.Equipments
	}
	return nil
}

// 装备物品请求
type EquipItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 背包物品ID
	Slot          int32                  `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`                   // 装备槽位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipItemRequest) Reset() {
	*x = EquipItemRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipItemRequest) ProtoMessage() {}

func (x *EquipItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipItemRequest.ProtoReflect.Descriptor instead.
func (*EquipItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{17}
}

func (x *EquipItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EquipItemRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *EquipItemRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

// 装备物品响应
type EquipItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipItemResponse) Reset() {
	*x = EquipItemResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipItemResponse) ProtoMessage() {}

func (x *EquipItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipItemResponse.ProtoReflect.Descriptor instead.
func (*EquipItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{18}
}

func (x *EquipItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EquipItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 卸下装备请求
type UnequipItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`                   // 装备槽位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipItemRequest) Reset() {
	*x = UnequipItemRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipItemRequest) ProtoMessage() {}

func (x *UnequipItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipItemRequest.ProtoReflect.Descriptor instead.
func (*UnequipItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{19}
}

func (x *UnequipItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnequipItemRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

// 卸下装备响应
type UnequipItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipItemResponse) Reset() {
	*x = UnequipItemResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipItemResponse) ProtoMessage() {}

func (x *UnequipItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipItemResponse.ProtoReflect.Descriptor instead.
func (*UnequipItemResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{20}
}

func (x *UnequipItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnequipItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取玩家信息
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 玩家ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取玩家信息
type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 玩家ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                    // 玩家名称
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                 // 等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserInfoResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 卡牌信息
type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 卡牌实例ID
	TemplateId    int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // 卡牌模板ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                // 卡牌名称
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                             // 卡牌等级
	Star          int32                  `protobuf:"varint,5,opt,name=star,proto3" json:"star,omitempty"`                               // 卡牌星级
	Activated     bool                   `protobuf:"varint,6,opt,name=activated,proto3" json:"activated,omitempty"`                     // 是否已激活
	Properties    string                 `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`                    // JSON格式的卡牌属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_internal_pb_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{23}
}

func (x *Card) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Card) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Card) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *Card) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *Card) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

// 获取玩家卡牌请求
type GetUserCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCardsRequest) Reset() {
	*x = GetUserCardsRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardsRequest) ProtoMessage() {}

func (x *GetUserCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCardsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserCardsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取玩家卡牌响应
type GetUserCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"` // 卡牌列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCardsResponse) Reset() {
	*x = GetUserCardsResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardsResponse) ProtoMessage() {}

func (x *GetUserCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCardsResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

// 激活卡牌请求
type ActivateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID
	TemplateId    int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // 卡牌模板ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateCardRequest) Reset() {
	*x = ActivateCardRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateCardRequest) ProtoMessage() {}

func (x *ActivateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateCardRequest.ProtoReflect.Descriptor instead.
func (*ActivateCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{26}
}

func (x *ActivateCardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ActivateCardRequest) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

// 激活卡牌响应
type ActivateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateCardResponse) Reset() {
	*x = ActivateCardResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateCardResponse) ProtoMessage() {}

func (x *ActivateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateCardResponse.ProtoReflect.Descriptor instead.
func (*ActivateCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{27}
}

func (x *ActivateCardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActivateCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 卡牌升级请求
type UpgradeCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	CardId        int64                  `protobuf:"varint,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"` // 卡牌ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeCardRequest) Reset() {
	*x = UpgradeCardRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCardRequest) ProtoMessage() {}

func (x *UpgradeCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCardRequest.ProtoReflect.Descriptor instead.
func (*UpgradeCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{28}
}

func (x *UpgradeCardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpgradeCardRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

// 卡牌升级响应
type UpgradeCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeCardResponse) Reset() {
	*x = UpgradeCardResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCardResponse) ProtoMessage() {}

func (x *UpgradeCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCardResponse.ProtoReflect.Descriptor instead.
func (*UpgradeCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{29}
}

func (x *UpgradeCardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpgradeCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 卡牌升星请求
type UpgradeCardStarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	CardId        int64                  `protobuf:"varint,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"` // 卡牌ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeCardStarRequest) Reset() {
	*x = UpgradeCardStarRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCardStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCardStarRequest) ProtoMessage() {}

func (x *UpgradeCardStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCardStarRequest.ProtoReflect.Descriptor instead.
func (*UpgradeCardStarRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{30}
}

func (x *UpgradeCardStarRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpgradeCardStarRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

// 卡牌升星响应
type UpgradeCardStarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeCardStarResponse) Reset() {
	*x = UpgradeCardStarResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCardStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCardStarResponse) ProtoMessage() {}

func (x *UpgradeCardStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCardStarResponse.ProtoReflect.Descriptor instead.
func (*UpgradeCardStarResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{31}
}

func (x *UpgradeCardStarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpgradeCardStarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 宠物信息
type Pet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 宠物实例ID
	TemplateId    int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // 宠物模板ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                // 宠物名称
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                             // 宠物等级
	Exp           int32                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`                                 // 当前经验
	IsBattle      bool                   `protobuf:"varint,6,opt,name=is_battle,json=isBattle,proto3" json:"is_battle,omitempty"`       // 是否出战
	Properties    string                 `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`                    // JSON格式的宠物属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pet) Reset() {
	*x = Pet{}
	mi := &file_internal_pb_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{32}
}

func (x *Pet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pet) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pet) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Pet) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Pet) GetIsBattle() bool {
	if x != nil {
		return x.IsBattle
	}
	return false
}

func (x *Pet) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

// 获取玩家宠物请求
type GetUserPetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPetsRequest) Reset() {
	*x = GetUserPetsRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPetsRequest) ProtoMessage() {}

func (x *GetUserPetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPetsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPetsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{33}
}

func (x *GetUserPetsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取玩家宠物响应
type GetUserPetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pets          []*Pet                 `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"` // 宠物列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPetsResponse) Reset() {
	*x = GetUserPetsResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPetsResponse) ProtoMessage() {}

func (x *GetUserPetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPetsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPetsResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{34}
}

func (x *GetUserPetsResponse) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

// 添加宠物请求
type AddPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID
	TemplateId    int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // 宠物模板ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPetRequest) Reset() {
	*x = AddPetRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetRequest) ProtoMessage() {}

func (x *AddPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetRequest.ProtoReflect.Descriptor instead.
func (*AddPetRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{35}
}

func (x *AddPetRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddPetRequest) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

// 添加宠物响应
type AddPetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPetResponse) Reset() {
	*x = AddPetResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetResponse) ProtoMessage() {}

func (x *AddPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetResponse.ProtoReflect.Descriptor instead.
func (*AddPetResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{36}
}

func (x *AddPetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 设置宠物出战状态请求
type SetPetBattleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
	PetId         int64                  `protobuf:"varint,2,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`          // 宠物ID
	IsBattle      bool                   `protobuf:"varint,3,opt,name=is_battle,json=isBattle,proto3" json:"is_battle,omitempty"` // 是否出战
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPetBattleStatusRequest) Reset() {
	*x = SetPetBattleStatusRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPetBattleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPetBattleStatusRequest) ProtoMessage() {}

func (x *SetPetBattleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPetBattleStatusRequest.ProtoReflect.Descriptor instead.
func (*SetPetBattleStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{37}
}

func (x *SetPetBattleStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetPetBattleStatusRequest) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *SetPetBattleStatusRequest) GetIsBattle() bool {
	if x != nil {
		return x.IsBattle
	}
	return false
}

// 设置宠物出战状态响应
type SetPetBattleStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPetBattleStatusResponse) Reset() {
	*x = SetPetBattleStatusResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPetBattleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPetBattleStatusResponse) ProtoMessage() {}

func (x *SetPetBattleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPetBattleStatusResponse.ProtoReflect.Descriptor instead.
func (*SetPetBattleStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{38}
}

func (x *SetPetBattleStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetPetBattleStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 增加宠物经验请求
type AddPetExpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	PetId         int64                  `protobuf:"varint,2,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`    // 宠物ID
	Exp           int32                  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`                     // 增加的经验值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPetExpRequest) Reset() {
	*x = AddPetExpRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPetExpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetExpRequest) ProtoMessage() {}

func (x *AddPetExpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetExpRequest.ProtoReflect.Descriptor instead.
func (*AddPetExpRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{39}
}

func (x *AddPetExpRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddPetExpRequest) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *AddPetExpRequest) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// 增加宠物经验响应
type AddPetExpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPetExpResponse) Reset() {
	*x = AddPetExpResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPetExpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetExpResponse) ProtoMessage() {}

func (x *AddPetExpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetExpResponse.ProtoReflect.Descriptor instead.
func (*AddPetExpResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{40}
}

func (x *AddPetExpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPetExpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 月签到信息
type MonthlySignInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`                                          // 年份
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`                                        // 月份
	SignDays      []int32                `protobuf:"varint,3,rep,packed,name=sign_days,json=signDays,proto3" json:"sign_days,omitempty"`           // 已签到的日期列表
	TotalSignDays int32                  `protobuf:"varint,4,opt,name=total_sign_days,json=totalSignDays,proto3" json:"total_sign_days,omitempty"` // 累计签到天数
	CanSignToday  bool                   `protobuf:"varint,5,opt,name=can_sign_today,json=canSignToday,proto3" json:"can_sign_today,omitempty"`    // 今日是否可以签到
	Today         int32                  `protobuf:"varint,6,opt,name=today,proto3" json:"today,omitempty"`                                        // 今日日期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlySignInfo) Reset() {
	*x = MonthlySignInfo{}
	mi := &file_internal_pb_user_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlySignInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlySignInfo) ProtoMessage() {}

func (x *MonthlySignInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlySignInfo.ProtoReflect.Descriptor instead.
func (*MonthlySignInfo) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{41}
}

func (x *MonthlySignInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MonthlySignInfo) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *MonthlySignInfo) GetSignDays() []int32 {
	if x != nil {
		return x.SignDays
	}
	return nil
}

func (x *MonthlySignInfo) GetTotalSignDays() int32 {
	if x != nil {
		return x.TotalSignDays
	}
	return 0
}

func (x *MonthlySignInfo) GetCanSignToday() bool {
	if x != nil {
		return x.CanSignToday
	}
	return false
}

func (x *MonthlySignInfo) GetToday() int32 {
	if x != nil {
		return x.Today
	}
	return 0
}

// 获取月签到信息请求
type GetMonthlySignInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlySignInfoRequest) Reset() {
	*x = GetMonthlySignInfoRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlySignInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlySignInfoRequest) ProtoMessage() {}

func (x *GetMonthlySignInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlySignInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlySignInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{42}
}

func (x *GetMonthlySignInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取月签到信息响应
type GetMonthlySignInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *MonthlySignInfo       `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"` // 月签到信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlySignInfoResponse) Reset() {
	*x = GetMonthlySignInfoResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlySignInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlySignInfoResponse) ProtoMessage() {}

func (x *GetMonthlySignInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlySignInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMonthlySignInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{43}
}

func (x *GetMonthlySignInfoResponse) GetInfo() *MonthlySignInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 月签到请求
type MonthlySignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlySignRequest) Reset() {
	*x = MonthlySignRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlySignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlySignRequest) ProtoMessage() {}

func (x *MonthlySignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlySignRequest.ProtoReflect.Descriptor instead.
func (*MonthlySignRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{44}
}

func (x *MonthlySignRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 月签到响应
type MonthlySignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	Rewards       []*Item                `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards,omitempty"`  // 签到奖励
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlySignResponse) Reset() {
	*x = MonthlySignResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlySignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlySignResponse) ProtoMessage() {}

func (x *MonthlySignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlySignResponse.ProtoReflect.Descriptor instead.
func (*MonthlySignResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{45}
}

func (x *MonthlySignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MonthlySignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MonthlySignResponse) GetRewards() []*Item {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// 领取月签到累计奖励请求
type ClaimMonthlySignRewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`                   // 累计天数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimMonthlySignRewardRequest) Reset() {
	*x = ClaimMonthlySignRewardRequest{}
	mi := &file_internal_pb_user_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimMonthlySignRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMonthlySignRewardRequest) ProtoMessage() {}

func (x *ClaimMonthlySignRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMonthlySignRewardRequest.ProtoReflect.Descriptor instead.
func (*ClaimMonthlySignRewardRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{46}
}

func (x *ClaimMonthlySignRewardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClaimMonthlySignRewardRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

// 领取月签到累计奖励响应
type ClaimMonthlySignRewardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	Rewards       []*Item                `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards,omitempty"`  // 奖励
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimMonthlySignRewardResponse) Reset() {
	*x = ClaimMonthlySignRewardResponse{}
	mi := &file_internal_pb_user_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimMonthlySignRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMonthlySignRewardResponse) ProtoMessage() {}

func (x *ClaimMonthlySignRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_user_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMonthlySignRewardResponse.ProtoReflect.Descriptor instead.
func (*ClaimMonthlySignRewardResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_user_proto_rawDescGZIP(), []int{47}
}

func (x *ClaimMonthlySignRewardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimMonthlySignRewardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClaimMonthlySignRewardResponse) GetRewards() []*Item {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_internal_pb_user_proto protoreflect.FileDescriptor

const file_internal_pb_user_proto_rawDesc = "" +
	"\n" +
	"\x16internal/pb/user.proto\x12\x04user\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"]\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"\xe1\x01\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x19\n" +
	"\bsub_type\x18\x06 \x01(\x05R\asubType\x12\x14\n" +
	"\x05color\x18\a \x01(\x05R\x05color\x12\x14\n" +
	"\x05stack\x18\b \x01(\x05R\x05stack\x12\x1a\n" +
	"\bequipped\x18\t \x01(\bR\bequipped\"I\n" +
	"\tInventory\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".user.ItemR\x05items\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\".\n" +
	"\x13GetInventoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"E\n" +
	"\x14GetInventoryResponse\x12-\n" +
	"\tinventory\x18\x01 \x01(\v2\x0f.user.InventoryR\tinventory\"V\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06tpl_id\x18\x02 \x01(\x03R\x05tplId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"+\n" +
	"\x0fAddItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"[\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\".\n" +
	"\x12RemoveItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"X\n" +
	"\x0eUseItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"+\n" +
	"\x0fUseItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x84\x01\n" +
	"\tEquipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\x05R\x04slot\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"properties\x18\x05 \x01(\tR\n" +
	"properties\"/\n" +
	"\x14GetEquipmentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"H\n" +
	"\x15GetEquipmentsResponse\x12/\n" +
	"\n" +
	"equipments\x18\x01 \x03(\v2\x0f.user.EquipmentR\n" +
	"equipments\"X\n" +
	"\x10EquipItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\x05R\x04slot\"G\n" +
	"\x11EquipItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x12UnequipItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\"I\n" +
	"\x13UnequipItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"X\n" +
	"\x13GetUserInfoResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\"\xb3\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x12\n" +
	"\x04star\x18\x05 \x01(\x05R\x04star\x12\x1c\n" +
	"\tactivated\x18\x06 \x01(\bR\tactivated\x12\x1e\n" +
	"\n" +
	"properties\x18\a \x01(\tR\n" +
	"properties\".\n" +
	"\x13GetUserCardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"8\n" +
	"\x14GetUserCardsResponse\x12 \n" +
	"\x05cards\x18\x01 \x03(\v2\n" +
	".user.CardR\x05cards\"O\n" +
	"\x13ActivateCardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\"J\n" +
	"\x14ActivateCardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12UpgradeCardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\x03R\x06cardId\"I\n" +
	"\x13UpgradeCardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x16UpgradeCardStarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\x03R\x06cardId\"M\n" +
	"\x17UpgradeCardStarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaf\x01\n" +
	"\x03Pet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x05R\x03exp\x12\x1b\n" +
	"\tis_battle\x18\x06 \x01(\bR\bisBattle\x12\x1e\n" +
	"\n" +
	"properties\x18\a \x01(\tR\n" +
	"properties\"-\n" +
	"\x12GetUserPetsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"4\n" +
	"\x13GetUserPetsResponse\x12\x1d\n" +
	"\x04pets\x18\x01 \x03(\v2\t.user.PetR\x04pets\"I\n" +
	"\rAddPetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\"D\n" +
	"\x0eAddPetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\x19SetPetBattleStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06pet_id\x18\x02 \x01(\x03R\x05petId\x12\x1b\n" +
	"\tis_battle\x18\x03 \x01(\bR\bisBattle\"P\n" +
	"\x1aSetPetBattleStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\x10AddPetExpRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06pet_id\x18\x02 \x01(\x03R\x05petId\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x05R\x03exp\"G\n" +
	"\x11AddPetExpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbc\x01\n" +
	"\x0fMonthlySignInfo\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1b\n" +
	"\tsign_days\x18\x03 \x03(\x05R\bsignDays\x12&\n" +
	"\x0ftotal_sign_days\x18\x04 \x01(\x05R\rtotalSignDays\x12$\n" +
	"\x0ecan_sign_today\x18\x05 \x01(\bR\fcanSignToday\x12\x14\n" +
	"\x05today\x18\x06 \x01(\x05R\x05today\"4\n" +
	"\x19GetMonthlySignInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"G\n" +
	"\x1aGetMonthlySignInfoResponse\x12)\n" +
	"\x04info\x18\x01 \x01(\v2\x15.user.MonthlySignInfoR\x04info\"-\n" +
	"\x12MonthlySignRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"o\n" +
	"\x13MonthlySignResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\arewards\x18\x03 \x03(\v2\n" +
	".user.ItemR\arewards\"L\n" +
	"\x1dClaimMonthlySignRewardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\"z\n" +
	"\x1eClaimMonthlySignRewardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\arewards\x18\x03 \x03(\v2\n" +
	".user.ItemR\arewards2\xb6\v\n" +
	"\vUserService\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12E\n" +
	"\fGetInventory\x12\x19.user.GetInventoryRequest\x1a\x1a.user.GetInventoryResponse\x126\n" +
	"\aAddItem\x12\x14.user.AddItemRequest\x1a\x15.user.AddItemResponse\x12?\n" +
	"\n" +
	"RemoveItem\x12\x17.user.RemoveItemRequest\x1a\x18.user.RemoveItemResponse\x126\n" +
	"\aUseItem\x12\x14.user.UseItemRequest\x1a\x15.user.UseItemResponse\x12H\n" +
	"\rGetEquipments\x12\x1a.user.GetEquipmentsRequest\x1a\x1b.user.GetEquipmentsResponse\x12<\n" +
	"\tEquipItem\x12\x16.user.EquipItemRequest\x1a\x17.user.EquipItemResponse\x12B\n" +
	"\vUnequipItem\x12\x18.user.UnequipItemRequest\x1a\x19.user.UnequipItemResponse\x12B\n" +
	"\vGetUserInfo\x12\x18.user.GetUserInfoRequest\x1a\x19.user.GetUserInfoResponse\x12E\n" +
	"\fGetUserCards\x12\x19.user.GetUserCardsRequest\x1a\x1a.user.GetUserCardsResponse\x12E\n" +
	"\fActivateCard\x12\x19.user.ActivateCardRequest\x1a\x1a.user.ActivateCardResponse\x12B\n" +
	"\vUpgradeCard\x12\x18.user.UpgradeCardRequest\x1a\x19.user.UpgradeCardResponse\x12N\n" +
	"\x0fUpgradeCardStar\x12\x1c.user.UpgradeCardStarRequest\x1a\x1d.user.UpgradeCardStarResponse\x12B\n" +
	"\vGetUserPets\x12\x18.user.GetUserPetsRequest\x1a\x19.user.GetUserPetsResponse\x123\n" +
	"\x06AddPet\x12\x13.user.AddPetRequest\x1a\x14.user.AddPetResponse\x12W\n" +
	"\x12SetPetBattleStatus\x12\x1f.user.SetPetBattleStatusRequest\x1a .user.SetPetBattleStatusResponse\x12<\n" +
	"\tAddPetExp\x12\x16.user.AddPetExpRequest\x1a\x17.user.AddPetExpResponse\x12W\n" +
	"\x12GetMonthlySignInfo\x12\x1f.user.GetMonthlySignInfoRequest\x1a .user.GetMonthlySignInfoResponse\x12B\n" +
	"\vMonthlySign\x12\x18.user.MonthlySignRequest\x1a\x19.user.MonthlySignResponse\x12c\n" +
	"\x16ClaimMonthlySignReward\x12#.user.ClaimMonthlySignRewardRequest\x1a$.user.ClaimMonthlySignRewardResponseB\rZ\vinternal/pbb\x06proto3"

var (
	file_internal_pb_user_proto_rawDescOnce sync.Once
	file_internal_pb_user_proto_rawDescData []byte
)

func file_internal_pb_user_proto_rawDescGZIP() []byte {
	file_internal_pb_user_proto_rawDescOnce.Do(func() {
		file_internal_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_user_proto_rawDesc), len(file_internal_pb_user_proto_rawDesc)))
	})
	return file_internal_pb_user_proto_rawDescData
}

var file_internal_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_internal_pb_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),                // 0: user.RegisterRequest
	(*RegisterResponse)(nil),               // 1: user.RegisterResponse
	(*LoginRequest)(nil),                   // 2: user.LoginRequest
	(*LoginResponse)(nil),                  // 3: user.LoginResponse
	(*Item)(nil),                           // 4: user.Item
	(*Inventory)(nil),                      // 5: user.Inventory
	(*GetInventoryRequest)(nil),            // 6: user.GetInventoryRequest
	(*GetInventoryResponse)(nil),           // 7: user.GetInventoryResponse
	(*AddItemRequest)(nil),                 // 8: user.AddItemRequest
	(*AddItemResponse)(nil),                // 9: user.AddItemResponse
	(*RemoveItemRequest)(nil),              // 10: user.RemoveItemRequest
	(*RemoveItemResponse)(nil),             // 11: user.RemoveItemResponse
	(*UseItemRequest)(nil),                 // 12: user.UseItemRequest
	(*UseItemResponse)(nil),                // 13: user.UseItemResponse
	(*Equipment)(nil),                      // 14: user.Equipment
	(*GetEquipmentsRequest)(nil),           // 15: user.GetEquipmentsRequest
	(*GetEquipmentsResponse)(nil),          // 16: user.GetEquipmentsResponse
	(*EquipItemRequest)(nil),               // 17: user.EquipItemRequest
	(*EquipItemResponse)(nil),              // 18: user.EquipItemResponse
	(*UnequipItemRequest)(nil),             // 19: user.UnequipItemRequest
	(*UnequipItemResponse)(nil),            // 20: user.UnequipItemResponse
	(*GetUserInfoRequest)(nil),             // 21: user.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),            // 22: user.GetUserInfoResponse
	(*Card)(nil),                           // 23: user.Card
	(*GetUserCardsRequest)(nil),            // 24: user.GetUserCardsRequest
	(*GetUserCardsResponse)(nil),           // 25: user.GetUserCardsResponse
	(*ActivateCardRequest)(nil),            // 26: user.ActivateCardRequest
	(*ActivateCardResponse)(nil),           // 27: user.ActivateCardResponse
	(*UpgradeCardRequest)(nil),             // 28: user.UpgradeCardRequest
	(*UpgradeCardResponse)(nil),            // 29: user.UpgradeCardResponse
	(*UpgradeCardStarRequest)(nil),         // 30: user.UpgradeCardStarRequest
	(*UpgradeCardStarResponse)(nil),        // 31: user.UpgradeCardStarResponse
	(*Pet)(nil),                            // 32: user.Pet
	(*GetUserPetsRequest)(nil),             // 33: user.GetUserPetsRequest
	(*GetUserPetsResponse)(nil),            // 34: user.GetUserPetsResponse
	(*AddPetRequest)(nil),                  // 35: user.AddPetRequest
	(*AddPetResponse)(nil),                 // 36: user.AddPetResponse
	(*SetPetBattleStatusRequest)(nil),      // 37: user.SetPetBattleStatusRequest
	(*SetPetBattleStatusResponse)(nil),     // 38: user.SetPetBattleStatusResponse
	(*AddPetExpRequest)(nil),               // 39: user.AddPetExpRequest
	(*AddPetExpResponse)(nil),              // 40: user.AddPetExpResponse
	(*MonthlySignInfo)(nil),                // 41: user.MonthlySignInfo
	(*GetMonthlySignInfoRequest)(nil),      // 42: user.GetMonthlySignInfoRequest
	(*GetMonthlySignInfoResponse)(nil),     // 43: user.GetMonthlySignInfoResponse
	(*MonthlySignRequest)(nil),             // 44: user.MonthlySignRequest
	(*MonthlySignResponse)(nil),            // 45: user.MonthlySignResponse
	(*ClaimMonthlySignRewardRequest)(nil),  // 46: user.ClaimMonthlySignRewardRequest
	(*ClaimMonthlySignRewardResponse)(nil), // 47: user.ClaimMonthlySignRewardResponse
}
var file_internal_pb_user_proto_depIdxs = []int32{
	4,  // 0: user.Inventory.items:type_name -> user.Item
	5,  // 1: user.GetInventoryResponse.inventory:type_name -> user.Inventory
	14, // 2: user.GetEquipmentsResponse.equipments:type_name -> user.Equipment
	23, // 3: user.GetUserCardsResponse.cards:type_name -> user.Card
	32, // 4: user.GetUserPetsResponse.pets:type_name -> user.Pet
	41, // 5: user.GetMonthlySignInfoResponse.info:type_name -> user.MonthlySignInfo
	4,  // 6: user.MonthlySignResponse.rewards:type_name -> user.Item
	4,  // 7: user.ClaimMonthlySignRewardResponse.rewards:type_name -> user.Item
	0,  // 8: user.UserService.Register:input_type -> user.RegisterRequest
	2,  // 9: user.UserService.Login:input_type -> user.LoginRequest
	6,  // 10: user.UserService.GetInventory:input_type -> user.GetInventoryRequest
	8,  // 11: user.UserService.AddItem:input_type -> user.AddItemRequest
	10, // 12: user.UserService.RemoveItem:input_type -> user.RemoveItemRequest
	12, // 13: user.UserService.UseItem:input_type -> user.UseItemRequest
	15, // 14: user.UserService.GetEquipments:input_type -> user.GetEquipmentsRequest
	17, // 15: user.UserService.EquipItem:input_type -> user.EquipItemRequest
	19, // 16: user.UserService.UnequipItem:input_type -> user.UnequipItemRequest
	21, // 17: user.UserService.GetUserInfo:input_type -> user.GetUserInfoRequest
	24, // 18: user.UserService.GetUserCards:input_type -> user.GetUserCardsRequest
	26, // 19: user.UserService.ActivateCard:input_type -> user.ActivateCardRequest
	28, // 20: user.UserService.UpgradeCard:input_type -> user.UpgradeCardRequest
	30, // 21: user.UserService.UpgradeCardStar:input_type -> user.UpgradeCardStarRequest
	33, // 22: user.UserService.GetUserPets:input_type -> user.GetUserPetsRequest
	35, // 23: user.UserService.AddPet:input_type -> user.AddPetRequest
	37, // 24: user.UserService.SetPetBattleStatus:input_type -> user.SetPetBattleStatusRequest
	39, // 25: user.UserService.AddPetExp:input_type -> user.AddPetExpRequest
	42, // 26: user.UserService.GetMonthlySignInfo:input_type -> user.GetMonthlySignInfoRequest
	44, // 27: user.UserService.MonthlySign:input_type -> user.MonthlySignRequest
	46, // 28: user.UserService.ClaimMonthlySignReward:input_type -> user.ClaimMonthlySignRewardRequest
	1,  // 29: user.UserService.Register:output_type -> user.RegisterResponse
	3,  // 30: user.UserService.Login:output_type -> user.LoginResponse
	7,  // 31: user.UserService.GetInventory:output_type -> user.GetInventoryResponse
	9,  // 32: user.UserService.AddItem:output_type -> user.AddItemResponse
	11, // 33: user.UserService.RemoveItem:output_type -> user.RemoveItemResponse
	13, // 34: user.UserService.UseItem:output_type -> user.UseItemResponse
	16, // 35: user.UserService.GetEquipments:output_type -> user.GetEquipmentsResponse
	18, // 36: user.UserService.EquipItem:output_type -> user.EquipItemResponse
	20, // 37: user.UserService.UnequipItem:output_type -> user.UnequipItemResponse
	22, // 38: user.UserService.GetUserInfo:output_type -> user.GetUserInfoResponse
	25, // 39: user.UserService.GetUserCards:output_type -> user.GetUserCardsResponse
	27, // 40: user.UserService.ActivateCard:output_type -> user.ActivateCardResponse
	29, // 41: user.UserService.UpgradeCard:output_type -> user.UpgradeCardResponse
	31, // 42: user.UserService.UpgradeCardStar:output_type -> user.UpgradeCardStarResponse
	34, // 43: user.UserService.GetUserPets:output_type -> user.GetUserPetsResponse
	36, // 44: user.UserService.AddPet:output_type -> user.AddPetResponse
	38, // 45: user.UserService.SetPetBattleStatus:output_type -> user.SetPetBattleStatusResponse
	40, // 46: user.UserService.AddPetExp:output_type -> user.AddPetExpResponse
	43, // 47: user.UserService.GetMonthlySignInfo:output_type -> user.GetMonthlySignInfoResponse
	45, // 48: user.UserService.MonthlySign:output_type -> user.MonthlySignResponse
	47, // 49: user.UserService.ClaimMonthlySignReward:output_type -> user.ClaimMonthlySignRewardResponse
	29, // [29:50] is the sub-list for method output_type
	8,  // [8:29] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_pb_user_proto_init() }
func file_internal_pb_user_proto_init() {
	if File_internal_pb_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_user_proto_rawDesc), len(file_internal_pb_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_user_proto_goTypes,
		DependencyIndexes: file_internal_pb_user_proto_depIdxs,
		MessageInfos:      file_internal_pb_user_proto_msgTypes,
	}.Build()
	File_internal_pb_user_proto = out.File
	file_internal_pb_user_proto_goTypes = nil
	file_internal_pb_user_proto_depIdxs = nil
}
