// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: internal/pb/ws.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebSocket 消息结构
type WSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // 服务名称
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`   // 方法名称
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Protocol Buffers 序列化后的数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	mi := &file_internal_pb_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_internal_pb_ws_proto_rawDescGZIP(), []int{0}
}

func (x *WSMessage) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WSMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WSMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_internal_pb_ws_proto protoreflect.FileDescriptor

const file_internal_pb_ws_proto_rawDesc = "" +
	"\n" +
	"\x14internal/pb/ws.proto\x12\x02ws\"W\n" +
	"\tWSMessage\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadB\rZ\vinternal/pbb\x06proto3"

var (
	file_internal_pb_ws_proto_rawDescOnce sync.Once
	file_internal_pb_ws_proto_rawDescData []byte
)

func file_internal_pb_ws_proto_rawDescGZIP() []byte {
	file_internal_pb_ws_proto_rawDescOnce.Do(func() {
		file_internal_pb_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_ws_proto_rawDesc), len(file_internal_pb_ws_proto_rawDesc)))
	})
	return file_internal_pb_ws_proto_rawDescData
}

var file_internal_pb_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_pb_ws_proto_goTypes = []any{
	(*WSMessage)(nil), // 0: ws.WSMessage
}
var file_internal_pb_ws_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_ws_proto_init() }
func file_internal_pb_ws_proto_init() {
	if File_internal_pb_ws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_ws_proto_rawDesc), len(file_internal_pb_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_ws_proto_goTypes,
		DependencyIndexes: file_internal_pb_ws_proto_depIdxs,
		MessageInfos:      file_internal_pb_ws_proto_msgTypes,
	}.Build()
	File_internal_pb_ws_proto = out.File
	file_internal_pb_ws_proto_goTypes = nil
	file_internal_pb_ws_proto_depIdxs = nil
}
