apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-cluster.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  redis.conf: |
    port {{ .Values.redis.port }}
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout {{ .Values.redis.config.clusterNodeTimeout }}
    appendonly {{ .Values.redis.config.appendonly }}
    appendfilename "{{ .Values.redis.config.appendfilename }}"
    appendfsync {{ .Values.redis.config.appendfsync }}
    maxmemory {{ .Values.redis.config.maxmemory }}
    maxmemory-policy {{ .Values.redis.config.maxmemoryPolicy }}
    timeout {{ .Values.redis.config.timeout }}
    tcp-keepalive {{ .Values.redis.config.tcpKeepalive }}
    loglevel {{ .Values.redis.config.loglevel }}
    logfile /data/redis.log
    protected-mode no
