{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "redis-cluster.fullname" . }}-network-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "redis-cluster.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "redis-cluster.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
    - protocol: TCP
      port: {{ .Values.redis.gossipPort }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.namespace }}
    ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "redis-cluster.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
    - protocol: TCP
      port: {{ .Values.redis.gossipPort }}
{{- end }}