apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  ports:
  - name: client
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}