apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mysql-cluster.fullname" . }}-pre-install
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: check-env
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          echo "Checking environment..."
          echo "Checking storage class..."
          if [ "{{ .Values.master.persistence.storageClassName }}" != "-" ]; then
            echo "Using storage class: {{ .Values.master.persistence.storageClassName }}"
          else
            echo "Using default storage class"
          fi
          echo "Environment check completed."
      restartPolicy: Never
  backoffLimit: 1
