apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: game-server
spec:
  clusterIP: None
  selector:
    app: nacos
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: game-server
spec:
  selector:
    app: nacos
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
  type: ClusterIP
