apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: grafana
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: 3000
  type: {{ .Values.grafana.service.type }}
