apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: prometheus
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: 9090
  type: {{ .Values.prometheus.service.type }}
