// Code generated by generate_proto_helpers. DO NOT EDIT.
package msgfactory

import (
	"fmt"

	"github.xubinbest.com/go-game-server/internal/pb"
	"google.golang.org/protobuf/proto"
)

func GetRequestMessageStruct(msgType string) (proto.Message, error) {
	switch msgType {
	case "game.joinGame":
		return &pb.JoinGameRequest{}, nil
	case "game.leaveGame":
		return &pb.LeaveGameRequest{}, nil
	case "game.gameState":
		return &pb.GameStateRequest{}, nil
	case "game.playerAction":
		return &pb.PlayerActionRequest{}, nil
	case "user.register":
		return &pb.RegisterRequest{}, nil
	case "user.login":
		return &pb.LoginRequest{}, nil
	case "user.getInventory":
		return &pb.GetInventoryRequest{}, nil
	case "user.addItem":
		return &pb.AddItemRequest{}, nil
	case "user.removeItem":
		return &pb.RemoveItemRequest{}, nil
	case "user.useItem":
		return &pb.UseItemRequest{}, nil
	case "user.getEquipments":
		return &pb.GetEquipmentsRequest{}, nil
	case "user.equipItem":
		return &pb.EquipItemRequest{}, nil
	case "user.unequipItem":
		return &pb.UnequipItemRequest{}, nil
	case "user.getUserInfo":
		return &pb.GetUserInfoRequest{}, nil
	case "user.getUserCards":
		return &pb.GetUserCardsRequest{}, nil
	case "user.activateCard":
		return &pb.ActivateCardRequest{}, nil
	case "user.upgradeCard":
		return &pb.UpgradeCardRequest{}, nil
	case "user.upgradeCardStar":
		return &pb.UpgradeCardStarRequest{}, nil
	case "user.getUserPets":
		return &pb.GetUserPetsRequest{}, nil
	case "user.addPet":
		return &pb.AddPetRequest{}, nil
	case "user.setPetBattleStatus":
		return &pb.SetPetBattleStatusRequest{}, nil
	case "user.addPetExp":
		return &pb.AddPetExpRequest{}, nil
	case "user.getMonthlySignInfo":
		return &pb.GetMonthlySignInfoRequest{}, nil
	case "user.monthlySign":
		return &pb.MonthlySignRequest{}, nil
	case "user.claimMonthlySignReward":
		return &pb.ClaimMonthlySignRewardRequest{}, nil
	case "leaderboard.reportScore":
		return &pb.ReportScoreRequest{}, nil
	case "leaderboard.getLeaderboard":
		return &pb.GetLeaderboardRequest{}, nil
	case "leaderboard.getRank":
		return &pb.GetRankRequest{}, nil
	case "social.sendChatMessage":
		return &pb.SendChatMessageRequest{}, nil
	case "social.getChatMessages":
		return &pb.GetChatMessagesRequest{}, nil
	case "social.getFriendList":
		return &pb.GetFriendListRequest{}, nil
	case "social.sendFriendRequest":
		return &pb.SendFriendRequestRequest{}, nil
	case "social.getFriendRequestList":
		return &pb.GetFriendRequestListRequest{}, nil
	case "social.handleFriendRequest":
		return &pb.HandleFriendRequestRequest{}, nil
	case "social.batchHandleFriendRequest":
		return &pb.BatchHandleFriendRequestRequest{}, nil
	case "social.deleteFriend":
		return &pb.DeleteFriendRequest{}, nil
	case "social.createGuild":
		return &pb.CreateGuildRequest{}, nil
	case "social.getGuildInfo":
		return &pb.GetGuildInfoRequest{}, nil
	case "social.getGuildMembers":
		return &pb.GetGuildMembersRequest{}, nil
	case "social.applyToGuild":
		return &pb.ApplyToGuildRequest{}, nil
	case "social.inviteToGuild":
		return &pb.InviteToGuildRequest{}, nil
	case "social.getGuildApplications":
		return &pb.GetGuildApplicationsRequest{}, nil
	case "social.handleGuildApplication":
		return &pb.HandleGuildApplicationRequest{}, nil
	case "social.kickGuildMember":
		return &pb.KickGuildMemberRequest{}, nil
	case "social.changeMemberRole":
		return &pb.ChangeMemberRoleRequest{}, nil
	case "social.transferGuildMaster":
		return &pb.TransferGuildMasterRequest{}, nil
	case "social.disbandGuild":
		return &pb.DisbandGuildRequest{}, nil
	case "social.leaveGuild":
		return &pb.LeaveGuildRequest{}, nil
	case "social.getGuildList":
		return &pb.GetGuildListRequest{}, nil
	default:
		return nil, fmt.Errorf("unknown request message type: %s", msgType)
	}
}

func GetResponseMessageStruct(msgType string) (proto.Message, error) {
	switch msgType {
	case "game.joinGame":
		return &pb.JoinGameResponse{}, nil
	case "game.leaveGame":
		return &pb.LeaveGameResponse{}, nil
	case "game.gameState":
		return &pb.GameStateResponse{}, nil
	case "game.playerAction":
		return &pb.PlayerActionResponse{}, nil
	case "user.register":
		return &pb.RegisterResponse{}, nil
	case "user.login":
		return &pb.LoginResponse{}, nil
	case "user.getInventory":
		return &pb.GetInventoryResponse{}, nil
	case "user.addItem":
		return &pb.AddItemResponse{}, nil
	case "user.removeItem":
		return &pb.RemoveItemResponse{}, nil
	case "user.useItem":
		return &pb.UseItemResponse{}, nil
	case "user.getEquipments":
		return &pb.GetEquipmentsResponse{}, nil
	case "user.equipItem":
		return &pb.EquipItemResponse{}, nil
	case "user.unequipItem":
		return &pb.UnequipItemResponse{}, nil
	case "user.getUserInfo":
		return &pb.GetUserInfoResponse{}, nil
	case "user.getUserCards":
		return &pb.GetUserCardsResponse{}, nil
	case "user.activateCard":
		return &pb.ActivateCardResponse{}, nil
	case "user.upgradeCard":
		return &pb.UpgradeCardResponse{}, nil
	case "user.upgradeCardStar":
		return &pb.UpgradeCardStarResponse{}, nil
	case "user.getUserPets":
		return &pb.GetUserPetsResponse{}, nil
	case "user.addPet":
		return &pb.AddPetResponse{}, nil
	case "user.setPetBattleStatus":
		return &pb.SetPetBattleStatusResponse{}, nil
	case "user.addPetExp":
		return &pb.AddPetExpResponse{}, nil
	case "user.getMonthlySignInfo":
		return &pb.GetMonthlySignInfoResponse{}, nil
	case "user.monthlySign":
		return &pb.MonthlySignResponse{}, nil
	case "user.claimMonthlySignReward":
		return &pb.ClaimMonthlySignRewardResponse{}, nil
	case "leaderboard.reportScore":
		return &pb.ReportScoreResponse{}, nil
	case "leaderboard.getLeaderboard":
		return &pb.GetLeaderboardResponse{}, nil
	case "leaderboard.getRank":
		return &pb.GetRankResponse{}, nil
	case "social.sendChatMessage":
		return &pb.SendChatMessageResponse{}, nil
	case "social.getChatMessages":
		return &pb.GetChatMessagesResponse{}, nil
	case "social.getFriendList":
		return &pb.GetFriendListResponse{}, nil
	case "social.sendFriendRequest":
		return &pb.SendFriendRequestResponse{}, nil
	case "social.getFriendRequestList":
		return &pb.GetFriendRequestListResponse{}, nil
	case "social.handleFriendRequest":
		return &pb.HandleFriendRequestResponse{}, nil
	case "social.batchHandleFriendRequest":
		return &pb.BatchHandleFriendRequestResponse{}, nil
	case "social.deleteFriend":
		return &pb.DeleteFriendResponse{}, nil
	case "social.createGuild":
		return &pb.CreateGuildResponse{}, nil
	case "social.getGuildInfo":
		return &pb.GetGuildInfoResponse{}, nil
	case "social.getGuildMembers":
		return &pb.GetGuildMembersResponse{}, nil
	case "social.applyToGuild":
		return &pb.ApplyToGuildResponse{}, nil
	case "social.inviteToGuild":
		return &pb.InviteToGuildResponse{}, nil
	case "social.getGuildApplications":
		return &pb.GetGuildApplicationsResponse{}, nil
	case "social.handleGuildApplication":
		return &pb.HandleGuildApplicationResponse{}, nil
	case "social.kickGuildMember":
		return &pb.KickGuildMemberResponse{}, nil
	case "social.changeMemberRole":
		return &pb.ChangeMemberRoleResponse{}, nil
	case "social.transferGuildMaster":
		return &pb.TransferGuildMasterResponse{}, nil
	case "social.disbandGuild":
		return &pb.DisbandGuildResponse{}, nil
	case "social.leaveGuild":
		return &pb.LeaveGuildResponse{}, nil
	case "social.getGuildList":
		return &pb.GetGuildListResponse{}, nil
	default:
		return nil, fmt.Errorf("unknown response message type: %s", msgType)
	}
}
