apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
        imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: {{ .Values.grafana.admin.user }}
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.grafana.admin.existingSecret }}
              key: {{ .Values.grafana.admin.passwordKey }}
        {{- if .Values.grafana.env }}
        {{- range $key, $value := .Values.grafana.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        resources:
          {{- toYaml .Values.grafana.resources | nindent 10 }}
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data
